# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget f2c blas lapack)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target f2c
add_library(f2c STATIC IMPORTED)

# Create imported target blas
add_library(blas STATIC IMPORTED)

# Create imported target lapack
add_library(lapack STATIC IMPORTED)

# Import target "f2c" for configuration "Debug"
set_property(TARGET f2c APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(f2c PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/F2CLIBS/libf2c/Debug/libf2c.lib"
  )

# Import target "blas" for configuration "Debug"
set_property(TARGET blas APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(blas PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "f2c"
  IMPORTED_LOCATION_DEBUG "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/BLAS/SRC/Debug/blas.lib"
  )

# Import target "lapack" for configuration "Debug"
set_property(TARGET lapack APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(lapack PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/SRC/Debug/lapack.lib"
  )

# Import target "f2c" for configuration "Release"
set_property(TARGET f2c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(f2c PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/F2CLIBS/libf2c/Release/libf2c.lib"
  )

# Import target "blas" for configuration "Release"
set_property(TARGET blas APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(blas PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "f2c"
  IMPORTED_LOCATION_RELEASE "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/BLAS/SRC/Release/blas.lib"
  )

# Import target "lapack" for configuration "Release"
set_property(TARGET lapack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(lapack PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/SRC/Release/lapack.lib"
  )

# Import target "f2c" for configuration "MinSizeRel"
set_property(TARGET f2c APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(f2c PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/F2CLIBS/libf2c/MinSizeRel/libf2c.lib"
  )

# Import target "blas" for configuration "MinSizeRel"
set_property(TARGET blas APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(blas PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "f2c"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/BLAS/SRC/MinSizeRel/blas.lib"
  )

# Import target "lapack" for configuration "MinSizeRel"
set_property(TARGET lapack APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(lapack PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/SRC/MinSizeRel/lapack.lib"
  )

# Import target "f2c" for configuration "RelWithDebInfo"
set_property(TARGET f2c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(f2c PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/F2CLIBS/libf2c/RelWithDebInfo/libf2c.lib"
  )

# Import target "blas" for configuration "RelWithDebInfo"
set_property(TARGET blas APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(blas PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "f2c"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/BLAS/SRC/RelWithDebInfo/blas.lib"
  )

# Import target "lapack" for configuration "RelWithDebInfo"
set_property(TARGET lapack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(lapack PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/yosef/Documents/Visual Studio 2017/Projects/libstruct/build_x64/SRC/RelWithDebInfo/lapack.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
